version: '3.8'

services:
  mcp-github-actions:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mcp-github-actions-server
    restart: unless-stopped
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"  # HTTP/WebSocket Zugriff
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Logging für besseres Debugging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Resource limits für Portainer
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

networks:
  mcp-network:
    driver: bridge

# Für Entwicklung - kann in Portainer ignoriert werden
volumes:
  mcp_logs:
    driver: local